name: ESOP Trading CI CD

on:
    push:
        branches: [pipeline]
    pull_request:
        branches: [pipeline]

jobs:
    terraform:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        outputs:
            output1: ${{ steps.get-ip.outputs.ip }}
        steps:
            - uses: actions/checkout@v3
            - uses: hashicorp/setup-terraform@v1


            - name: Terraform Formatting
              id: fmt
              run: terraform fmt -check

            - name: Terraform Init
              id: init
              run: terraform init

            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color

            - name: Terraform Plan
              id: plan
              run: |
                  plan_output=$(terraform plan -no-color -input=false -var "key=${{ secrets.SSH_PRIVATE_KEY }}")
                  echo "plan_output<<EOF" >> $GITHUB_OUTPUT
                  echo "$plan_output" >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT
              continue-on-error: true

            - name: Terraform Apply
              run: terraform apply -auto-approve -input=false -var="key=${{ secrets.SSH_PRIVATE_KEY }}"

            - name: Terraform output
              id: get-ip
              run: echo "ip=$(terraform output instance_public_ip | tr -d '"')" >> $GITHUB_OUTPUT

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - run: pwd
            - run: ./gradlew test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - run: ./gradlew build

            - name: Upload jar to artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: application-jar
                  path: build/libs/esop-trading-0.1-all.jar

    deploy:
        runs-on: ubuntu-latest
        needs: [build, terraform]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: application-jar
            - run: ls -a

            - name: copy artifact to the server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ needs.terraform.outputs.output1 }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  source: "esop-trading-0.1-all.jar,startup.sh"
                  target: "~"

            - name: start the application
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ needs.terraform.outputs.output1 }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  script: "chmod 700 startup.sh &&  sudo nohup./ ./startup.sh > /dev/null &"
