name: ESOP Trading CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-github-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: ./gradlew test