name: ESOP Trading CI CD

on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ pipeline ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
      - run: pwd
      - run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: ./gradlew build

      - name: Upload jar to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: application-jar
          path: build/libs/esop-trading-0.1-all.jar


  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: application-jar

      - name: executing remote ssh commands using ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./application-jar"
          target: "application-jar"
