name: ESOP Trading CI CD

on:
    push:
        branches: [pipeline]
    pull_request:
        branches: [pipeline]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - run: pwd
            - run: ./gradlew test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
            - run: ./gradlew build

            - name: Upload jar to artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: application-jar
                  path: build/libs/esop-trading-0.1-all.jar

    deploy:
        runs-on: ubuntu-latest
        needs: [build]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/download-artifact@v3
              with:
                  name: application-jar
            - run: ls -a

            - name: copy artifact to the server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ needs.terraform.outputs.output1 }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  source: "esop-trading-0.1-all.jar,startup.sh"
                  target: "~"

            - name: start the application
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ needs.terraform.outputs.output1 }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  script: "chmod 700 startup.sh &&  sudo nohup./ ./startup.sh > /dev/null &"
