name: ESOP Trading CI CD

on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ pipeline ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
      - run: pwd
      - run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: pwd
      - run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create SSH key
        run: |
            mkdir -p ~/.ssh/
            echo "$SSH_KEY" > ../private.key
            sudo chmod 600 ../private.key
            echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
            SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
            SSH_KEY_PATH: ${{ github.workspace }}/../private.key
      - run: ssh ec2-user@ec2-65-2-38-32.ap-south-1.compute.amazonaws.com