name: ESOP Trading CI CD

on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ pipeline ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
      - run: pwd
      - run: ./gradlew test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: pwd
      - run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          USERNAME: ec2-user
          HOSTNAME: ec2-65-2-38-32.ap-south-1.compute.amazonaws.com
      - run: echo "$SSH_KEY" > private_key && chmod 600 private_key
      - run: cat private_key
      - run: ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME}
      - run: echo "Hello world!" > hello