name: ESOP Trading CI CD

on:
    push:
        branches: [infra]
    pull_request:
        branches: [infra]

jobs:
    plan:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        outputs:
            output1: ${{ steps.get-ip.outputs.ip }}
        steps:
            - uses: actions/checkout@v3
            - run: which terraform
            - name: Terraform Formatting
              id: fmt
              run: terraform fmt -check

            - name: Terraform Init
              id: init
              run: terraform init

            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color

            - name: Terraform Plan
              id: plan
              run: |
                  plan_output=$(terraform plan -no-color -input=false -var "key=${{ secrets.SSH_PRIVATE_KEY }}")
                  echo "plan_output<<EOF" >> $GITHUB_OUTPUT
                  echo "$plan_output" >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT
              continue-on-error: true

    apply:
        needs: plan
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        outputs:
            output1: ${{ steps.get-ip.outputs.ip }}
        
        steps:
            - name: Terraform Apply

              run: terraform apply -auto-approve -input=false -var="key=${{ secrets.SSH_PRIVATE_KEY }}"

            - name: Terraform output
              id: get-ip
              run: echo "ip=$(terraform output instance_public_ip | tr -d '"')" >> $GITHUB_OUTPUT
