name: terraform apply

on:
    workflow_dispatch:

jobs:
    terraform:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        outputs:
            output1: ${{ steps.get-ip.outputs.ip }}
        steps:
            - uses: actions/checkout@v3
            - name: Terraform Formatting
              id: fmt
              run: terraform fmt -check
    
            - name: Terraform Init
              id: init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve -input=false -var="key=${{ secrets.SSH_PRIVATE_KEY }}"

            - name: Terraform output
              id: get-ip
              run: echo "ip=$(terraform output instance_public_ip | tr -d '"')" >> $GITHUB_OUTPUT